//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.DAL.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class bra01branches
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bra01branches()
        {
            this.emp01employee = new HashSet<emp01employee>();
            this.usr05users = new HashSet<usr05users>();
        }
    
        public int bra01uin { get; set; }
        public string bra01name { get; set; }
        public string bra01address { get; set; }
        public string bra01telephone { get; set; }
        public bool bra01status { get; set; }
        public bool bra01deleted { get; set; }
        public string bra01code { get; set; }
        public string bra01created_by { get; set; }
        public string bra01created_name { get; set; }
        public System.DateTime bra01created_date_eng { get; set; }
        public string bra01created_date_nep { get; set; }
        public string bra01updated_by { get; set; }
        public System.DateTime bra01updated_date_eng { get; set; }
        public string bra01updated_date_nep { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<emp01employee> emp01employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usr05users> usr05users { get; set; }
    }
}
