//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.DAL.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class cfg01configurations
    {
        public string cfg01uin { get; set; }
        public string cfg01module { get; set; }
        public string cfg01key { get; set; }
        public string cfg01value { get; set; }
        public System.DateTime cfg01created_date { get; set; }
        public string cfg01created_name { get; set; }
        public string cfg01updated_name { get; set; }
        public System.DateTime cfg01updated_date { get; set; }
    }
}
