//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.DAL.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class dep01department
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dep01department()
        {
            this.emp01employee = new HashSet<emp01employee>();
        }
    
        public int dep01uin { get; set; }
        public string dep01title { get; set; }
        public string dep01code { get; set; }
        public bool dep01status { get; set; }
        public bool dep01deleted { get; set; }
        public string dep01updated_by { get; set; }
        public System.DateTime dep01updated_date_eng { get; set; }
        public string dep01updated_date_nep { get; set; }
        public string dep01created_by { get; set; }
        public System.DateTime dep01created_date_eng { get; set; }
        public string dep01created_date_nep { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<emp01employee> emp01employee { get; set; }
    }
}
