//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.DAL.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class des01designations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public des01designations()
        {
            this.emp01employee = new HashSet<emp01employee>();
        }
    
        public int des01uin { get; set; }
        public string des01title { get; set; }
        public string des01description { get; set; }
        public bool des01status { get; set; }
        public bool des01deleted { get; set; }
        public string des01created_by { get; set; }
        public string des01created_date_nep { get; set; }
        public System.DateTime des01created_date_eng { get; set; }
        public string des01updated_by { get; set; }
        public string des01updated_date_nep { get; set; }
        public System.DateTime des01updated_date_eng { get; set; }
        public string des01code { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<emp01employee> emp01employee { get; set; }
    }
}
