//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.DAL.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class emp01employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public emp01employee()
        {
            this.usr05users = new HashSet<usr05users>();
        }
    
        public int emp01uin { get; set; }
        public string emp01code { get; set; }
        public int emp01des01uin { get; set; }
        public int emp01dep01uin { get; set; }
        public int emp01lvl01uin { get; set; }
        public int emp01bra01uin { get; set; }
        public string emp01name { get; set; }
        public string emp01join_date_nep { get; set; }
        public System.DateTime emp01join_date_eng { get; set; }
        public string emp01address { get; set; }
        public string emp01email { get; set; }
        public string emp01mobile { get; set; }
        public bool emp01status { get; set; }
        public bool emp01deleted { get; set; }
        public string emp01created_by { get; set; }
        public System.DateTime emp01created_date_eng { get; set; }
        public string emp01created_date_nep { get; set; }
        public string emp01updated_by { get; set; }
        public string emp01updated_date_nep { get; set; }
        public System.DateTime emp01update_date_eng { get; set; }
    
        public virtual bra01branches bra01branches { get; set; }
        public virtual dep01department dep01department { get; set; }
        public virtual des01designations des01designations { get; set; }
        public virtual lvl01employee_levels lvl01employee_levels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usr05users> usr05users { get; set; }
    }
}
