//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.DAL.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCode
    {
        public long id { get; set; }
        public string user_id { get; set; }
        public string email { get; set; }
        public System.DateTime requested_date { get; set; }
        public System.DateTime valid_till_date { get; set; }
        public string ip { get; set; }
        public long code { get; set; }
        public bool CodeUsed { get; set; }
    }
}
