//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.DAL.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class usr05users
    {
        public string usr05userId { get; set; }
        public int usr05bra01uin { get; set; }
        public byte usr05type { get; set; }
        public bool usr05status { get; set; }
        public bool usr05deleted { get; set; }
        public System.DateTime usr05created_date { get; set; }
        public string usr05created_by { get; set; }
        public System.DateTime usr05updated_date { get; set; }
        public string usr05updated_by { get; set; }
        public Nullable<int> usr05emp01uin { get; set; }
        public bool usr05can_view_all_branch { get; set; }
    
        public virtual bra01branches bra01branches { get; set; }
        public virtual emp01employee emp01employee { get; set; }
    }
}
