using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DMS.Helpers
{
    public static class PasswordHelper
    {
        public static string GetAutoGeneratedPassword()
        {
            int PasswordLength = 10;
            string _allowedChars = "0123456789abcdefghijkmnopqrstuvwxyzABCDEFGHJKLMNOPQRSTUVWXYZ";
            Random randNum = new Random();
            char[] chars = new char[PasswordLength];
            int allowedCharCount = _allowedChars.Length;
            for (int i = 0; i < PasswordLength; i++)
            {
                chars[i] = _allowedChars[(int)((_allowedChars.Length) * randNum.NextDouble())];
            }
            return new string(chars);
        }
    }
}